### ISSUE TITLE
Error in ProbDenseInput

### ISSUE THREAD

**Issue by sebp** [marcoancona/DASP#1]
First of all, thank you very much for making your code available online.

I experimented with your example for Parkinson and realized that approximated Shapley values are getting worse when increasing the batch size in [the predict call](https://github.com/marcoancona/DASP/blob/master/dasp/dasp.py#L46).

After further inspecting the code, I realized that ProbDenseInput only used the first element of the `k` vector passed to it (which accounts of the coalition size). Thus, results would only be correct if all elements in one batch have the same coalition size. With the default batch size of 32, this is mostly true, and errors aren't very obvious, but if increasing batch size to thousands, the approximation becomes strikingly bad. Therefore, I believe instead of multiplying by `k[0,0]` in `ProbDenseInput.call`, values should be multiplied by the whole vector `k` instead.

**Comment by marcoancona** [comment]
Hi! The only reason why `k` is a vector and not a scalar is that Keras requires all inputs to the network to have the same batch size. However, the `call` method should propagate distributions assuming the same coalition size for all elements in the batch, hence we multiply by the first element in the `k` vector. Multiplying by the vector would not change the result as all elements in `k` are the same (constructed with `K.repeat()`) https://github.com/marcoancona/DASP/blob/860ad5aebb28950902b4cd5edc6b7a0a08f84a91/dasp/dasp.py#L45

> Thus, results would only be correct if all elements in one batch have the same coalition size

I am not sure I understand what you mean here. Elements in the batch do not *have* a coalition size. The coalition size is passed to the `call` method from the caller and applied to all elements of the batch. 

Nevertheless, the batch size should have no influence whatsoever on the result so I need to investigate this behavior.

**Comment by sebp** [comment]
I have to admit, I'm not entirely sure why `np.tile` and `np.repeat` are necessary. What I did find out running the current code is that `ks` is a list of integers (for the Parkinson example at least) and `np.repeat` duplicates them:
```python
>>> ks = np.array([0, 1, 2, 3, 4, 5, 6, 7])
>>> np.repeat(ks, 11)
array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17])
```
The call to `self.dasp_model.predict(inputs)` then splits the inputs into batches, which in this particular case would require a batch size of 11 for each batch to have the same `k`, otherwise the batch would span multiple values for `k`, but only the first one would be used. With the default batch size of 32, the first batch would contain `k` ranging from 0 to 2, but only 0 would be used in `ProbDenseInput.call`.

**Comment by marcoancona** [comment]
Oh, I misunderstood your first message. Yes, it should multiply the entire vector `k`. I have fixed it now and also exposed a `batch_size` param for `dasp.run()`.
