### ISSUE TITLE
Seems error in Equation (7) in Arxiv paper

### ISSUE THREAD

**Issue by GlowingHorse** [marcoancona/DASP#2]
Based on the paper you referred and your pseudo-code, equation (7) should be <img src="http://chart.googleapis.com/chart?cht=tx&chl= Z_j\sim\mathcal{N}\left ( k\mu _j,k{\sigma}^2_j\frac{k-1}{N-1}  \right )" style="border:none;">. 
If it is a typo-error, you could update the version next time inArxiv.

**Comment by GlowingHorse** [comment]
Would you mind telling me the software you used for your artistic figure.1 in the DASP paper (Origin or something else) ? 
Thanks!

**Comment by marcoancona** [comment]
Regarding the first question, the equation in the last version of the Arxive paper is correct. The factor that multiplies the variance is `(N-k)/(N-1)`:  if `k=N` variance becomes 0 as the sum of all the features is always the same; if `k=1` the variance of the sum if equal to the variance of the population as we are effectively sampling a single element. Does it make sense?

Regarding the second question, the plots were generated with the `matplotlib` library and arranged together using Sketch for macOS.
